### ISSUE TITLE
Needs credit to dragonfire535/xiao.

### ISSUE THREAD

**Issue by dragonfire535** [KamranMackey/Erica#16]
There's some obvious takes from my bot, Xiao, in here, as far as even using some of the images I have on Imgur (`https://i.imgur.com/Z7NJBK2.png` in Wikipedia, for example). All you need to do is add a credit line to the README and I'll be happy. Something like this:

> Some commands were inspired by and based on commands from [Xiao by dragonfire535](https://github.com/dragonfire535/xiao).

**Comment by KamranMackey** [comment]
Hey,

I have added the respective credit to the README. I should've done that sooner and for that I apologize. Your bot is really neat by the way.

Closing the issue as I think the issue has been resolved now.
